/** Doc URLs for stack tags on project cards */
export const TECH_DOCS_URLS: Readonly<Record<string, string>> = {
  TestRail: "https://www.testrail.com/",
  "JavaScript/TypeScript": "https://www.typescriptlang.org/docs/",
  Playwright: "https://playwright.dev/",
  CircleCI: "https://circleci.com/docs/",
  K6: "https://k6.io/docs/",
  Postman: "https://learning.postman.com/docs/",
  Protractor: "https://www.protractortest.org/#/",
  TeamCity: "https://www.jetbrains.com/help/teamcity/",
  JavaScript: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/",
  QACoverage: "https://smartbear.com/product/testcomplete/",
  Powershell: "https://learn.microsoft.com/en-us/powershell/",
  TestComplete: "https://smartbear.com/product/testcomplete/",
  WinAppDriver: "https://github.com/microsoft/WinAppDriver",
  WDIO: "https://webdriver.io/docs/gettingstarted/",
  "Github Actions": "https://docs.github.com/en/actions",
  VirtualBox: "https://www.virtualbox.org/manual/",
  QEMU: "https://www.qemu.org/docs/master/",
  AIW: "https://accessibilityinsights.io/docs/en/web/overview/",
  TypeScript: "https://www.typescriptlang.org/docs/",
  React: "https://react.dev/",
  "Node.js": "https://nodejs.org/docs/",
};
